const LOG_RECEIPTS_LOADED_MESSAGE = 'Загружено квитанций'
const LOG_CONTEXT_MESSAGE = 'Контекст'
const LOG_PERIOD_MESSAGE = 'Период'
const LOG_PDF_RECEIPTS_COUNT_MESSAGE = 'PDF квитанции'
const LOG_CONDO_SAVE_MESSAGE = 'Сохранение в CONDO:'
const LOG_CONDO_UPDATED_RECEIPTS_COUNT_MESSAGE = 'Обновлено'
const LOG_CONDO_CREATED_RECEIPTS_COUNT_MESSAGE = 'Добавлено'
const LOG_CONDO_UNTOUCHED_RECEIPTS_COUNT_MESSAGE = 'Не изменились'
const LOG_CONDO_ERROR_RECEIPTS_COUNT_MESSAGE = 'Ошибок'
const PDF_CREATE_MESSAGE = 'Новых'
const PDF_UPDATE_MESSAGE = 'Обновлено'
const PDF_SKIPP_MESSAGE = 'Без изменений'
const PDF_ERROR_MESSAGE = 'Ошибок'

module.exports = {
    LOG_CONDO_SAVE_MESSAGE,
    LOG_RECEIPTS_LOADED_MESSAGE,
    LOG_CONDO_ERROR_RECEIPTS_COUNT_MESSAGE,
    LOG_CONDO_UPDATED_RECEIPTS_COUNT_MESSAGE,
    LOG_CONDO_CREATED_RECEIPTS_COUNT_MESSAGE,
    LOG_CONDO_UNTOUCHED_RECEIPTS_COUNT_MESSAGE,
    LOG_CONTEXT_MESSAGE,
    LOG_PERIOD_MESSAGE,
    LOG_PDF_RECEIPTS_COUNT_MESSAGE,
    PDF_CREATE_MESSAGE,
    PDF_UPDATE_MESSAGE,
    PDF_SKIPP_MESSAGE,
    PDF_ERROR_MESSAGE,
}